name: Build & Deploy Astro to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build Astro site
        run: npm run build

      - name: Copy build to /docs
        run: |
          rm -rf docs
          mkdir docs
          cp -R dist/* docs/
          touch docs/.nojekyll

      - name: Commit and push /docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs .nojekyll
          git commit -m "ci: deploy to /docs [skip ci]" || echo "No changes to commit"
          git push origin main
